osx_image: xcode8.3

dist: trusty
sudo: required

language: node_js
node_js:
  - 8

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - secure: 'NMzZu8g1zUFa/0e4p7JF8t+cEwl7D8r2PFvPoyzoR/pWVkDUwJvsp9zta2SBGKNKKwlrFjQ9ZVNIB/Z3It5itKRJDtLsS44QZdWUjKlVNM5qwXbvRFX+aquJYqSa2eMmsM/hCfjEIaPRzbknwP1S2WGimGUGOW2XYUC5vvSIDPKwcn8GUdJ/CtZ6Bm4vnrvBk+WVkeOPB8KQbKutLRM4dutj7nUWTq0ZMlXuWM4y8fRMeZTrUMOk3BhxOeeRur6xZ3nVOsxhgtl6kKb+d0tAQtFfnRekQkSB/qSdF/BZfV6jpABNr05LI76VkSXbFXmDwqSt5Sw8ZMxxJo+Wzc8anzUVGzmNscCHm9/ewqXlh4laWbT59NTiJ1ayGdewydSa02dehxUNmbBZXI2bGCOgEE8Z5LlgCpcQN2HtQ+qCQSc9hjk12sYLiTkGQ3J49Mx3Q3Yo2vjrIXKp/x0V42oDniNP9rzSMKOfrCOBf6GLaOTsk8kOU0ao62ieUHpGRBZBBDWf3Cgud9/qr+cnqWWCdelDbvm5BwksLfYApLfdUwBFogEKWdlmh4BHc5U1nFu3+upYRi1EV5nrDmwE5YzkugxkESe5GzN3h9GjkEU2bZmwGBj9cIjqQlLn0/rxjebiHfLianjXWPu8nv8sS6EjRnyWz/IwjzHqgTycFmDU8yg='

os:
  - osx

cache:
  directories:
  - node_modules
  - app/node_modules
  - '$HOME/.cache/electron'
  - '$HOME/.cache/electron-builder'
  - '$HOME/.npm/_prebuilds'

install:
  - npm install

script:
  - npm run build

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

deploy:
  - provider: releases
    api_key:
      secure: 'LvIAo9Z5yfpnS7eyEzyrOyGM5cnWtJRQgcZKkscOLwwPD+pfQuK6XRvtb9UzJAMWQIFZJ/YxYBukJkYj2gn+TYYBlqIouLU5dnEr5Nlj2BcZZbohDxiMasApYEwCXJHGW1KfLbrlF0PY2aCHmbjXYaF9cvTybHUlGIxHI74e1qqBPQI0hM6DsQfWACdlc2mIPhx7TwLX0A6obO0aEcWBNkqbAoNJgPukZjo2Eh/HvGM2zCHiq/aw3gTO8ma+kDYN8Wr03xfUDtfqFw0B+A13liOVtESgGPCMWwxFh+KKtgOtf4tU6qJqvghmt0cCA0+gEWVv7Tr1d8vFwWgTGwO8ZZPw6bQE8zzVcqUZvoKGhJQiT3YZOwLSpuGYpudp59NKEofNlkckJz7y0dE/46fFnKfgXyfkDkMruGQI+4ZofTTTVe6PdnnBEc2DjUoWO8/PcRLurc2KfDYyzwh2KI7/3E2Xh3Ocyu7mrWbInfx2Yf8J6j8ZDgk48s7V+3jkDr1S1ym8Oq2EcQ2ArPrsG3O2OjUIEJPMxyPPbdjmsvqbx5wZS2aBwf5QE3rAgVMFijZx/T5gQ8CcZrykP6uHNeTLd2k5I9UYNB/XroTTpq6ZQGKuwfx+Es6ptctRofYmRzTiGVQlvE/lZYz0GxtgbzcqtOlaCj9iTmDX5/z77SLLdXo='
    file_glob: true
    file:
    - dist/*.txt
    skip_cleanup: true
    on:
      tags: true
